[package]
name = "sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite" ] }
tokio = { version = "1", features = ["full"] }
